# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  # dynamic_date_url: www.federalregister.gov/api/v1/documents.json?per_page=1000&order=relevance&conditions%5Bpublication_date%5D%5Bgte%5D= + ((Date.today - 4.months).to_s) + &conditions%5Btype%5D%5B%5D=PRORULE&conditions%5Btype%5D%5B%5D=NOTICE&conditions%5Bsignificant%5D=1
  secret_key_base: d99cb892853a0c2485a0fc71bad9d4b32079d1fa2cc27ecd0e21f0c79e9f6e89a3d876a33362d24440750969ead6d8ea45d4f478d3266757d2816826958e70a5

test:
  secret_key_base: 9d602454bdea573cc5c7948013a64e24e8cb93d0756b6e61a4d64b84fe110d8ff3699ce11a0ecba05551d67273db727d4ac1df6c50ceacb22a4d0c35cb4525a1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
