

comments = Comment.create([
  { description: 'comment comment comment comment', citizen_id: 1, action_id: 1 },
  { description: 'comment comment comment comment', citizen_id: 2, action_id: 1 },
  { description: 'comment comment comment comment', citizen_id: 5, action_id: 1 },
  { description: 'comment comment comment comment', citizen_id: 2, action_id: 1 },
  { description: 'comment comment comment comment', citizen_id: 4, action_id: 10 },
  { description: 'comment comment comment comment', citizen_id: 4, action_id: 5 },
  { description: 'comment comment comment comment', citizen_id: 3, action_id: 5 },
  { description: 'comment comment comment comment', citizen_id: 3, action_id: 4 },
  { description: 'comment comment comment comment', citizen_id: 5, action_id: 3 },
  { description: 'comment comment comment comment', citizen_id: 1, action_id: 2 },
  { description: 'comment comment comment comment', citizen_id: 2, action_id: 2 },
  { description: 'comment comment comment comment', citizen_id: 4, action_id: 2 },
  { description: 'comment comment comment comment', citizen_id: 4, action_id: 3 },
  { description: 'comment comment comment comment', citizen_id: 8, action_id: 4 },
  { description: 'comment comment comment comment', citizen_id: 10, action_id: 1 },
  { description: 'comment comment comment comment', citizen_id: 7, action_id: 1 },
  { description: 'comment comment comment comment', citizen_id: 6, action_id: 1 },
  { description: 'comment comment comment comment', citizen_id: 6, action_id: 10 },
  { description: 'comment comment comment comment', citizen_id: 6, action_id: 9 },
  { description: 'comment comment comment comment', citizen_id: 7, action_id: 9 },
  { description: 'comment comment comment comment', citizen_id: 7, action_id: 8 },
  { description: 'comment comment comment comment', citizen_id: 10, action_id: 8 },
  { description: 'comment comment comment comment', citizen_id: 10, action_id: 6 },
  { description: 'comment comment comment comment', citizen_id: 10, action_id: 7 },
  { description: 'comment comment comment comment', citizen_id: 9, action_id: 7 },
  { description: 'comment comment comment comment', citizen_id: 8, action_id: 7 }
  ])

  accounts = Account.create([
  {email: 'email1@sample.com', password: 'password', password_confirmation: 'password'},
  {email: 'email2@sample.com', password: 'password', password_confirmation: 'password'},
  {email: 'email3@sample.com', password: 'password', password_confirmation: 'password'},
  {email: 'email4@sample.com', password: 'password', password_confirmation: 'password'},
  {email: 'email5@sample.com', password: 'password', password_confirmation: 'password'},
  {email: 'email6@sample.com', password: 'password', password_confirmation: 'password'},
  {email: 'email7@sample.com', password: 'password', password_confirmation: 'password'},
  {email: 'email8@sample.com', password: 'password', password_confirmation: 'password'},
  {email: 'email9@sample.com', password: 'password', password_confirmation: 'password'},
  {email: 'email0@sample.com', password: 'password', password_confirmation: 'password'}
  ])

  citizens = Citizen.create([
       {account_id: 1,name: 'Luke', location:'NJ', age:28, gender:'m'},
       {account_id:2,name: 'Laia', location:'NY', age:38, gender:'f'},
       {account_id:3,name: 'Lisa', location:'MD', age:18, gender:'f'},
       {account_id:4,name: 'Chewie', location:'ND', age:25, gender:'m'},
       {account_id:5,name: 'Marge', location:'MO', age:35, gender:'f'},
       {account_id:6,name: 'Frank', location:'NY', age:28, gender:'m'},
       {account_id:7,name: 'Homer', location:'CA', age:42, gender:'m'},
       {account_id:8,name: 'Scott', location:'TX', age:20, gender:'m'},
       {account_id:9,name: 'Bart', location:'CO', age:18, gender:'m'},
       {account_id:10,name: 'Moe', location:'MN', age:28, gender:'m'}
       ])

 votes = Vote.create([

    {vote: "down",citizen_id:2,action_id:1},
    {vote: "down",citizen_id:5,action_id:1},
    {vote: "up",citizen_id:15,action_id:1},
    {vote: "down",citizen_id:4,action_id:1},
    {vote: "up",citizen_id:8,action_id:1},
    {vote: "up",citizen_id:3,action_id:2},
    {vote: "up",citizen_id:5,action_id:2},
    {vote: "up",citizen_id:19,action_id:2},
    {vote: "up",citizen_id:1,action_id:3},
    {vote: "up",citizen_id:2,action_id:3},
    {vote: "up",citizen_id:17,action_id:3},
    {vote: "up",citizen_id:18,action_id:3},
    {vote: "up",citizen_id:6,action_id:4},
    {vote: "up",citizen_id:1,action_id:4},
    {vote: "up",citizen_id:3,action_id:4},
    {vote: "up",citizen_id:7,action_id:4},
    {vote: "up",citizen_id:9,action_id:5},
    {vote: "up",citizen_id:10,action_id:5},
    {vote: "up",citizen_id:11,action_id:5},
    {vote: "up",citizen_id:12,action_id:2},
    {vote: "up",citizen_id:13,action_id:5},
    {vote: "up",citizen_id:14,action_id:5},
    {vote: "up",citizen_id:16,action_id:5},
])
categories = Category.create ([
  {name: "education"},
  {name: "not-included"},
  {name: "health"},
  {name: "transportation"},
  {name: "labor"},
  {name: "security"},
  {name: "energy"},
  {name: "veterans"},
  {name: "finance"},
  {name: "housing"},
  {name: "foreign_policy"},
  {name: "law_and_justice"},
  {name: "technology"},
])

actions = Action.create ([
  {
    :title => 'Extension of the Workers Compensation Offset From Age 65 to Full Retirement Age—Achieving a Better Life Experience (ABLE) Act',
    :summary => 'We propose to amend our regulations to incorporate changes made by the ABLE Act to section 224(a) of the Social Security Act. The ABLE Act amends section 224(a) by changing the age at which disability insurance benefits (DIB) are no longer subject to reduction (offset) based on receipt of workers compensation or public disability benefits (WC/PDB), from age 65 to the day the individual attains full retirement age. This change will make our rules consistent with the provisions of the Act, as amended by the ABLE Act.',
    :desc => 'Proposed Rule',
    :agency_acronym => 'SSA',
    :agency_full => 'Social Security Administration',
    :category_name => 'labor',
    :significant => false,
    :publication_date => Date.new(2016, 1, 4),
    :document_number => '2015-33036',
    :fedregister_id => '81 FR 41',
    :cfr => '20 CFR 404',
    :docket_id => 'SSA-2015-0018',
    :open_for_comment => false,
    :comments_received => 0,
    :comment_end_date => Date.new(2016,2,3),
    :contact => 'Dean Dwight, Office of Income Security Programs, Social Security Administration, 6401 Security Boulevard, Baltimore, MD 21235-6401, (410) 966-7161.',
    :tags => ['retirement', 'disability', 'insurance'],
    :html_url => 'https://www.federalregister.gov/documents/2016/01/04/2015-33036/extension-of-the-workers-compensation-offset-from-age-65-to-full-retirement-age-achieving-a-better',
  },
  {
    :title => "Improvements to Benchmarks and Related Requirements Governing Hearing Aid-Compatible Mobile Handsets",
    :summary => "In this document, the Federal Communications Commission (Commission) seeks comment on revisions to the Commission's wireless hearing aid compatibility rules. The Commission proposes to adopt a consensus approach developed cooperatively by consumer advocates and industry trade associations, which would require manufacturers and service providers to increase the percentage of new wireless handset models that are hearing aid compatible over time, culminating in a system in which all wireless handset models are accessible to people with hearing loss.",
    :desc => 'Proposed Rule',
    :agency_acronym => 'FCC',
    :agency_full => 'Federal Communications Commission',
    :category_name => 'technology',
    :significant => false,
    :publication_date => Date.new(2016,1,5),
    :document_number => '2015-32756',
    :fedregister_id => '81 FR 204',
    :cfr => '47 CFR 20',
    :docket_id => 'FCC 15-155',
    :open_for_comment => true,
    :comment_end_date => Date.new(2016,1,14),
    :tags=> ["Communications common carrirs", "Communications equipment", "Radio"],
    :html_url => "https://www.federalregister.gov/documents/2016/01/05/2015-32756/improvements-to-benchmarks-and-related-requirements-governing-hearing-aid-compatible-mobile-handsets"
  },
  {
    :title => 'Energy Conservation Program: Energy Conservation Standards for Walk-In Cooler and Freezer Refrigeration Systems',
    :summary => "The Energy Policy and Conservation Act of 1975 (“EPCA”), as amended, prescribes energy conservation standards for various consumer products and certain commercial and industrial equipment, including walk-in coolers and walk-in freezers. This final rule details a series of energy conservation standards pertaining to certain discrete classes of refrigeration systems used in this equipment. These standards, which are consistent with recommendations presented by a working group that included refrigeration system manufacturers, installers, and energy efficiency advocates, have been determined to result in the significant conservation of energy and achieve the maximum improvement in energy efficiency that is technologically feasible and economically justified.",
    :desc => 'Rule',
    :agency_acronym => 'DOE',
    :agency_full => 'Department of Energy',
    :category_name => 'energy',
    :significant => true,
    :priority_category => 'Economically Significant',
    :action => 'Final Rule',
    :effective_date => Date.new(2017,9,8),
    :publication_date => Date.new(2017,7,10),
    :document_number => '2017-14079',
    :fedregister_id => '81 FR 204',
    :rin => '1904-AD59',
    :cfr => '10 CFR 431',
    :docket_id => 'EERE-2015-BT-STD-0016',
    :open_for_comment => true,
    :comments_received => 30,
    :comments_url => 'https://www.regulations.gov/docketBrowser?rpp=50&so=DESC&sb=postedDate&po=0&dct=PS&D=EERE-2015-BT-STD-0016',
    :start_page => 31808,
    :supporting_docs_number => 74,
    :contact => 'Ashley Armstrong, U.S. Department of Energy, Office of Energy Efficiency and Renewable Energy, Building Technologies Office, EE-5B, 1000 Independence Avenue SW., Washington, DC 20585-0121. Telephone: (202) 586-6590. Email: walk-in_coolers_and_walk-in_freezers@ee.doe.gov.',
    :tags=> ["Administrative practice and procedure", "Confidential business information", "Energy conservation",  "Intergovernmental relations", "Small businesses"],
    :html_url => "https://www.federalregister.gov/documents/full_text/html/2017/07/10/2017-14079.html"
  },
  {
    :title => 'Definition of Employee Pension Benefit Plan Under ERISA',
    :summary => "Under the Congressional Review Act, Congress has passed, and the President has signed resolutions of disapproval of Savings Arrangements Established by States for Non-Governmental Employees and Savings Arrangements Established by Qualified State Political Subdivisions for Non-Governmental Employees, as codified in the Code of Federal Regulations. The Employee Benefits Security Administration (EBSA) published these final rules in 2016, effective October 31, 2016 and January 19, 2017, respectively. Because these resolutions invalidate these final rules, EBSA is hereby removing these final rules from the Code of Federal Regulations.",
    :desc => 'Rule',
    :agency_acronym => 'DOL',
    :agency_id => 271,
    :agency_full => 'Department of Labor',
    :subagency => 'Employee Benefits Security Administration',
    :subagency_id => 131,
    :category_name => 'labor',
    :effective_date => Date.new(2017,6,28),
    :significant => true,
    :priority_category => 'Other Significant',
    :action => 'Final rule; CRA Revocation.',
    :publication_date => Date.new(2017,6,28),
    :document_number => '2017-13459',
    :fedregister_id => '82 FR 29236',
    :rin => '1210-AB76',
    :cfr => '29 CFR 2510',
    :docket_id => 'EBSA-2016-0012',
    :open_for_comment => false,
    :comments_received => 27,
    :comments_url => "https://www.regulations.gov/docketBrowser?rpp=50&so=DESC&sb=postedDate&po=0&dct=PS&D=EBSA-2016-0012",
    :start_page => 29236,
    :supporting_docs_number => 0,
    :tags=> ["Accounting", "Employee benefit plans", "Reporting and recordkeeping requirements"],
    :html_url => "https://www.federalregister.gov/documents/full_text/html/2017/06/28/2017-13459.html"
  },
  {
    :title => 'Medicare Program; Part B Drug Payment Model; Withdrawal',
    :summary => "This document withdraws a proposed rule that was published in the Federal Register on March 11, 2016. The proposed rule discussed our proposal to implement a new Medicare payment model under section 1115A of the Social Security Act (the Act).",
    :desc => 'Proposed Rule',
    :agency_acronym => 'HHS',
    :agency_id => 221,
    :agency_full => 'Department of Health and Human Services',
    :subagency => 'Centers for Medicare & Medicaid Services',
    :subagency_id => 45,
    :category_name => 'health',
    :significant => true,
    :priority_category => 'Economically Significant',
    :action => 'Withdrawal of proposed rule.',
    :publication_date => Date.new(2017,10,4),
    :document_number => '2017-21420',
    :fedregister_id => '82 FR 46182',
    :rin => '0938-AS85',
    :regulation_title => "Medicare Program; Part B Drug Payment Model (CMS-1670-P)",
    :cfr => '29 CFR 2510',
    :docket_id => 'CMS-1670-WN',
    :open_for_comment => false,
    :comments_received => 1350,
    :comments_url => "https://www.regulations.gov/docketBrowser?rpp=50&so=DESC&sb=postedDate&po=0&dct=PS&D=CMS-2016-0036",
    :start_page => 46182,
    :supporting_docs_number => 0,
    :tags => ['Medicare', 'Social Security Act'],
    :html_url => "https://www.federalregister.gov/documents/full_text/html/2017/10/04/2017-21420.html"
  },
  {
    :title => 'Proprietary Trading and Certain Interests in and Relationships With Covered Funds (Volcker Rule); Request for Public Input',
    :summary => "The OCC is seeking the public's input with this request for information to assist in determining how the final rule implementing section 13 of the Bank Holding Company Act (commonly referred to as the ``Volcker Rule'') should be revised to better accomplish the purposes of the statute. The OCC also solicits comments suggesting improvements in the ways in which the final rule has been applied and administered to date. This OCC request is limited to regulatory actions that may be undertaken to achieve these objectives. The OCC is not requesting comment on changes to the underlying Volcker statute. The OCC recognizes that any revision to the final rule or the administration of that rule must be done consistent with the constraints of the statute and requests that commenters provide input that fits within the contours of that structure.",
    :desc => 'Proposed Rule',
    :agency_id => 497,
    :agency_full => 'Department of the Treasury',
    :subagency => 'Office of the Comptroller of the Currency',
    :subagency_id => 80,
    :category_name => 'finance',
    :significant => false,
    :action => 'Request for information.',
    :publication_date => Date.new(2017,8,7),
    :document_number => '2017-16556',
    :fedregister_id => '82 FR 36692',
    :rin => nil,
    :regulation_title => "Request for Comment on the Volcker Rule",
    :cfr => '12 CFR 44',
    :docket_id => 'OCC-2017-0014',
    :open_for_comment => true,
    :comments_received => 67,
    :comments_url => "https://www.regulations.gov/docketBrowser?rpp=50&so=DESC&sb=postedDate&po=0&dct=PS&D=OCC-2017-0014",
    :comment_end_date => Date.new(2017,9,21),
    :start_page => 36692,
    :contact => 'Ted Dowd, Director; Suzette Greco, Assistant Director; Tabitha Edgens, Senior Attorney; Mark OHoro, Attorney, Securities and Corporate Practices Division, (202) 649-5510; Patrick Tierney, Assistant Director, Legislative and Regulatory Activities Division, (202) 649-5490, 400 7th Street SW., Washington, DC 20219.',
    :tags => ['Dodd Frank', 'financial reform'],
    :html_url => "https://www.federalregister.gov/documents/full_text/html/2017/08/07/2017-16556.html"
  },
  {
    :title => "Notice of Petitions by Firms for Determination of Eligibility To Apply for Trade Adjustment Assistance",
    :summary => "The Economic Development Administration (EDA) has received petitions for certification of eligibility to apply for Trade Adjustment Assistance from the firms listed below. Accordingly, EDA has initiated investigations to determine whether increased imports into the United States of articles like or directly competitive with those produced by each of these firms contributed importantly to the total or partial separation of the firm's workers, or threat thereof, and to a decrease in sales or production of each petitioning firm.",
    :desc => 'Notice',
    :agency_acronym => 'DOC',
    :agency_id => 54,
    :agency_full => 'Department of Commerce',
    :subagency => 'Economic Development Administration',
    :subagency_id => 120,
    :category_name => 'finance',
    :significant => false,
    :action => 'Request for information.',
    :publication_date => Date.new(2017,10,10),
    :document_number => '2017-21656',
    :fedregister_id => '82 FR 46961',
    :rin => nil,
    :open_for_comment => false,
    :start_page => 46961,
    :contact => 'Ted Dowd, Director; Suzette Greco, Assistant Director; Tabitha Edgens, Senior Attorney; Mark OHoro, Attorney, Securities and Corporate Practices Division, (202) 649-5510; Patrick Tierney, Assistant Director, Legislative and Regulatory Activities Division, (202) 649-5490, 400 7th Street SW., Washington, DC 20219.',
    :tags => ['Trade Adjustment Assistance', 'Petitions'],
    :html_url => "https://www.federalregister.gov/documents/full_text/html/2017/10/10/2017-21656.html"
  },
  {
    :title => 'Significant New Use Rules on Certain Chemical Substances',
    :summary =>  "EPA is promulgating significant new use rules (SNURs) under the Toxic Substances Control Act (TSCA) for 37 chemical substances which were the subject of premanufacture notices (PMNs). The applicable review periods for the PMNs submitted for these 37 chemical substances all ended prior to June 22, 2016 (i.e., the date on which President Obama signed into law the Frank R. Lautenberg Chemical Safety for the 21st Century Act which amends TSCA). Six of these chemical substances are subject to TSCA section 5(e) consent orders issued by EPA. This action requires persons who intend to manufacture (defined by statute to include import) or process any of these 37 chemical substances for an activity that is designated as a significant new use by this rule to notify EPA at least 90 days before commencing that activity. The required notification initiates EPA's evaluation of the intended use within the applicable review period. Manufacture and processing for the significant new use is unable to commence until EPA has conducted a review of the notice, made an appropriate determination on the notice, and take such actions as are required with that determination.",
    :desc => 'Rule',
    :agency_acronym => 'EPA',
    :agency_id => 145,
    :agency_full => 'Environmental Protection Agency',
    :category_name => 'energy',
    :effective_date => Date.new(2017,11,20),
    :significant => false,
    :priority_category => "Routine and Frequent",
    :action => 'Direct final rule.',
    :publication_date => Date.new(2017,9,21),
    :document_number => '2017-20158',
    :fedregister_id => '82 FR 44079',
    :rin => '2070-AB27',
    :regulation_title => "Significant New Use Rule (SNUR); Chemical-Specific SNURs To Extend Provisions of Section 5(e) Orders",
    :cfr => ['40 CFR 721', '40 CFR 9'],
    :docket_id => ["EPA-HQ-OPPT-2016-0331", "FRL-9959-81"],
    :comments_url => 'https://www.regulations.gov/#!submitComment;D=EPA-HQ-OPPT-2016-0331-0001',
    :start_page => 44079,
    :supporting_docs_number => 145,
    :tags => ["Chemicals", "Environmental protection", "Hazardous substances", "Reporting and recordkeeping requirements"],
    :html_url => "https://www.federalregister.gov/documents/full_text/html/2017/09/21/2017-20158.html",
  },

  ])
